language: java
env:
  matrix:
    - TARGET_PLATFORM=helios
    - TARGET_PLATFORM=indigo
    - TARGET_PLATFORM=juno
before_install:
  - wget http://dl.google.com/android/android-sdk_r22.0.1-linux.tgz
  - tar -zxf android-sdk_r22.0.1-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  - echo yes |android update sdk --filter platform-tools,build-tools-17.0.0,android-10,android-7,extra-android-support,sysimg-16 --no-ui --force > /dev/null
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: mvn --file me.gladwell.eclipse.m2e.android.test/pom.xml -Dtarget.platform=$TARGET_PLATFORM verify
